module.exports=[
    {
        category:"场均得分",
        detailUrl:"http://nba.stats.qq.com/stats/detail/?order=defen&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/201935.png",
                playerName:"詹姆斯-哈登",
                teamName:"火箭",
                score:115.6
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203078.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    },
    {
        category:"场均篮板",
        detailUrl:"http://nba.stats.qq.com/stats/detail/?order=lanban&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/203083.png",
                playerName:"安德鲁-德拉蒙德",
                teamName:"活塞",
                score:15.8
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203991.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203507.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    },
    {
        category:"场均助攻",
        detailUrl:"http://nba.stats.qq.com/stats/detail/?order=zhugong&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/2544.png",
                playerName:"勒布朗-詹姆斯",
                teamName:"湖人",
                score:10.2
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203078.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    },
    {
        category:"场均抢断",
        detailUrl:"https://nba.stats.qq.com/stats/detail/?order=qiangduan&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/201935.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203078.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    },
    {
        category:"场均盖帽",
        detailUrl:"https://nba.stats.qq.com/stats/detail/?order=gaimao&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/201935.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203078.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    },
    {
        category:"场均失误",
        detailUrl:"https://nba.stats.qq.com/stats/detail/?order=shiwu&type=player",
        playerTop3:[
            {
                num:1,
                playerImg:"http://nbachina.qq.com/media/img/players/silos/220x350/201935.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:2,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203078.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            },
            {
                num:3,
                playerImg:"https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                playerName:"扬尼斯-阿德托昆博",
                teamName:"凯尔特人",
                score:115.6
            }
        ]
    }
]