module.exports={
    category: "场均得分",
    detailUrl:"https://nba.stats.qq.com/stats/detail/?order=defen&type=team",
    teamOption: mvpData.threeScore,
    teamList:[{
                num:1,
                img:"http://mat1.gtimg.com/sports/nba/logo/1602/15.png",
                name:"密尔沃基雄鹿",
                score:118.7
              },
              {
                num:2,
                img:"http://mat1.gtimg.com/sports/nba/logo/1602/10.png",
                name:"休斯顿火箭",
                score:117.8
              },
              {
                num:3,
                img:"http://mat1.gtimg.com/sports/nba/logo/1602/10.png",
                name:"休斯顿火箭",
                score:117.8
              },
              {
                num:4,
                img:"http://mat1.gtimg.com/sports/nba/logo/1602/10.png",
                name:"休斯顿火箭",
                score:117.8
              },
              {
                num:5,
                img:"http://mat1.gtimg.com/sports/nba/logo/1602/6.png",
                name:"达拉斯独行侠",
                score:117.0
            }]
}